import "@/styles/globals.css"
import { Providers } from "./providers"
import { fontSans } from "@/config/fonts"
import clsx from "clsx"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js"
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={clsx("font-sans antialiased", fontSans.className)}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
